// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dsmrwxucwnmfochyctfz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRzbXJ3eHVjd25tZm9jaHljdGZ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0Mzk5MTcsImV4cCI6MjA1OTAxNTkxN30.StLeeykOKoFVspyOx0uuNnSSsLYArZ0PtaDnt5PbQi0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);